language: node_js
cache:
  directories:
    - "node_modules"
script:
  - npm run snapshot
  - npm run build
deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL_ADDRESS
    api_key: $NPM_AUTH_TOKEN
    on:
      branch: master
      tags: true
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
      tags: true
branches:
  only:
    - master
notifications:
  email:
    on_success: never
