language: node_js
cache:
  directories:
    - "node_modules"
script: npm run snapshot
deploy:
  - provider: pages
    local-dir: storybook-static
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
      tags: true
  - provider: npm
    email: $NPM_EMAIL_ADDRESS
    api_key: $NPM_AUTH_TOKEN
    on:
      branch: master
      tags: true
branches:
  only:
    - master
    - /^([0-9]+)\.([0-9]+)\.([0-9]+)$/
notifications:
  email:
    on_success: never
