name: Deploy to Zeit Now

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Deploy to Zeit Now
        uses: amondnet/now-deployment@v1
        with:
          zeit-token: ${{ secrets.NOW_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          zeit-team-id: team_Gi3q9d0m9gDtYn8A74EbZGnD
