name: Deploy to Zeit Now

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Deploy to Zeit Now
        run: yarn run deploy
        env:
          NOW_TOKEN: ${{secrets.NOW_TOKEN}}
